### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by KooroshRH** [wangkaihong/Unsup_Recycle_GAN#12]
Hi,

I hope you are doing well. I wanted to know about the data structure in this project. Can I use multiple sequences of frames in the 'path/to/data/' mentioned structure? As much as I know from your instruction, we have to use a single video for A and a single video for B domains (same for validation).
Also, what was your GPU setup for training of this project, and how many iterations does it take to train the model in viper-to-cityscapes mode?

**Comment by wangkaihong** [comment]
Thanks for your interest! One of the major contributions of this work is to eliminate the necessity to train a model on multiple sequences of frames as we take it as a constraint rather than a reinforcement. So the short answer is no, it's not necessary to.

Any GPU with 12 GB memory should be sufficient for our default setting.  V2C experiments take 2 epochs for training, and V2L experiments take 5 epochs. The number of iterations depends on the size of the dataset.

**Comment by KooroshRH** [comment]
Hi again,

I have another question about the last topic. How many frames did you use for each sequence in viper-to-cityscapes mode? In other words, I'm looking for a reasonable estimate of the required iterations for a good result. Also, is there any difference between the sequence size for your proposed model and cycleGAN or recycleGAN?
