### ISSUE TITLE
different in test and train

### ISSUE THREAD

**Issue by lx123-j** [wangkaihong/Unsup_Recycle_GAN#5]
Thank you for your last answer, and there is another question to ask,  so there are different in the train and test? In the train,I only get the random picture, but in the test I will get the pictures which is the frame in the video?

**Comment by wangkaihong** [comment]
There are certainly a lot of differences between the behaviors of training and testing, and yes, in the training phase you will get shuffled random frames from training videos while in the testing phase, you will have unshuffled data from the testing videos so that you can place them in the correct order.
